/**
 * Superplatform
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DockerSvcLaunchContainerOptions } from './dockerSvcLaunchContainerOptions';

export class DockerSvcLaunchContainerRequest {
    /**
    * HostPort is the port on the host machine that will be mapped to the container\'s port
    */
    'hostPort'?: number;
    /**
    * Image is the Docker image to use for the container
    */
    'image': string;
    /**
    * Options provides additional options for launching the container
    */
    'options'?: DockerSvcLaunchContainerOptions;
    /**
    * Port is the port number that the container will expose
    */
    'port': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "hostPort",
            "baseName": "hostPort",
            "type": "number"
        },
        {
            "name": "image",
            "baseName": "image",
            "type": "string"
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "DockerSvcLaunchContainerOptions"
        },
        {
            "name": "port",
            "baseName": "port",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return DockerSvcLaunchContainerRequest.attributeTypeMap;
    }
}

