/**
 * Singulatron
 * Run and develop self-hosted AI apps. Your programmable in-house GPT. The Firebase for the AI age.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class DockerSvcLaunchOptions {
    'envs'?: Array<string>;
    'gpuEnabled'?: boolean;
    'hash'?: string;
    'hostBinds'?: Array<string>;
    'labels'?: { [key: string]: string; };
    'name'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "envs",
            "baseName": "envs",
            "type": "Array<string>"
        },
        {
            "name": "gpuEnabled",
            "baseName": "gpuEnabled",
            "type": "boolean"
        },
        {
            "name": "hash",
            "baseName": "hash",
            "type": "string"
        },
        {
            "name": "hostBinds",
            "baseName": "hostBinds",
            "type": "Array<string>"
        },
        {
            "name": "labels",
            "baseName": "labels",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DockerSvcLaunchOptions.attributeTypeMap;
    }
}

