/**
 * Superplatform
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class DockerSvcLaunchContainerOptions {
    /**
    * Assets maps environment variable names to file URLs. Example: {\"MODEL\": \"https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.2-GGUF/resolve/main/mistral-7b-instruct-v0.2.Q2_K.gguf\"} These files are downloaded by the Download Svc and mounted in the container. The environment variable `MODEL` will point to the local file path in the container.
    */
    'assets'?: { [key: string]: string; };
    /**
    * Envs are environment variables to set in the container
    */
    'envs'?: Array<string>;
    /**
    * GPUEnabled specifies if GPU support is enabled
    */
    'gpuEnabled'?: boolean;
    /**
    * Hash is a unique identifier for the container
    */
    'hash'?: string;
    /**
    * Keeps are paths that persist across container restarts. They function like mounts or volumes, but their external storage location is irrelevant.
    */
    'keeps'?: Array<string>;
    /**
    * Labels are metadata labels associated with the container
    */
    'labels'?: { [key: string]: string; };
    /**
    * Name is the name of the container
    */
    'name'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "assets",
            "baseName": "assets",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "envs",
            "baseName": "envs",
            "type": "Array<string>"
        },
        {
            "name": "gpuEnabled",
            "baseName": "gpuEnabled",
            "type": "boolean"
        },
        {
            "name": "hash",
            "baseName": "hash",
            "type": "string"
        },
        {
            "name": "keeps",
            "baseName": "keeps",
            "type": "Array<string>"
        },
        {
            "name": "labels",
            "baseName": "labels",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DockerSvcLaunchContainerOptions.attributeTypeMap;
    }
}

