/**
 * Superplatform
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DatastoreFilter } from './datastoreFilter';
import { DynamicSvcObject } from './dynamicSvcObject';

export class DynamicSvcUpdateObjectRequest {
    'filters'?: Array<DatastoreFilter>;
    'object'?: DynamicSvcObject;
    'table'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "filters",
            "baseName": "filters",
            "type": "Array<DatastoreFilter>"
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "DynamicSvcObject"
        },
        {
            "name": "table",
            "baseName": "table",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DynamicSvcUpdateObjectRequest.attributeTypeMap;
    }
}

