/**
 * Superplatform
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DynamicSvcObject } from './dynamicSvcObject';

export class DynamicSvcQueryResponse {
    'objects'?: Array<DynamicSvcObject>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "objects",
            "baseName": "objects",
            "type": "Array<DynamicSvcObject>"
        }    ];

    static getAttributeTypeMap() {
        return DynamicSvcQueryResponse.attributeTypeMap;
    }
}

