/**
 * Singulatron
 * Run and develop self-hosted AI apps. Your programmable in-house GPT. The Firebase for the AI age.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DatastoreCondition } from './datastoreCondition';
import { GenericSvcGenericObject } from './genericSvcGenericObject';

export class GenericSvcUpdateObjectRequest {
    'conditions'?: Array<DatastoreCondition>;
    'object'?: GenericSvcGenericObject;
    'table'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "conditions",
            "baseName": "conditions",
            "type": "Array<DatastoreCondition>"
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "GenericSvcGenericObject"
        },
        {
            "name": "table",
            "baseName": "table",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return GenericSvcUpdateObjectRequest.attributeTypeMap;
    }
}

