/**
 * Singulatron
 * AI management and development platform.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GenericSvcGenericObjectCreateFields } from './genericSvcGenericObjectCreateFields';

export class GenericSvcCreateObjectRequest {
    'object'?: GenericSvcGenericObjectCreateFields;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "GenericSvcGenericObjectCreateFields"
        }    ];

    static getAttributeTypeMap() {
        return GenericSvcCreateObjectRequest.attributeTypeMap;
    }
}

