/**
 * Superplatform
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class RegistrySvcRegisterServiceInstanceRequest {
    /**
    * Host of the service instance address. Required if URL is not provided
    */
    'host'?: string;
    /**
    * IP of the service instance address. Optional: to register by IP instead of host
    */
    'ip'?: string;
    /**
    * Path of the service instance address. Optional (e.g., \"/api\")
    */
    'path'?: string;
    /**
    * Port of the service instance address. Required if URL is not provided
    */
    'port'?: number;
    /**
    * Scheme of the service instance address. Required if URL is not provided.
    */
    'scheme'?: string;
    /**
    * The User Svc slug of the service whose instance is being registered.
    */
    'slug': string;
    /**
    * Full address URL of the service instance.
    */
    'url'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "host",
            "baseName": "host",
            "type": "string"
        },
        {
            "name": "ip",
            "baseName": "ip",
            "type": "string"
        },
        {
            "name": "path",
            "baseName": "path",
            "type": "string"
        },
        {
            "name": "port",
            "baseName": "port",
            "type": "number"
        },
        {
            "name": "scheme",
            "baseName": "scheme",
            "type": "string"
        },
        {
            "name": "slug",
            "baseName": "slug",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RegistrySvcRegisterServiceInstanceRequest.attributeTypeMap;
    }
}

