/**
 * Superplatform
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RegistrySvcAPISpec } from './registrySvcAPISpec';
import { RegistrySvcClient } from './registrySvcClient';
import { RegistrySvcImageSpec } from './registrySvcImageSpec';

export class RegistrySvcServiceDefinition {
    /**
    * API Specs such as OpenAPI definitions etc.
    */
    'apiSpecs'?: Array<RegistrySvcAPISpec>;
    'clients'?: Array<RegistrySvcClient>;
    /**
    * Container specifications for Docker, K8s, etc.                                        // Programming language clients.
    */
    'image'?: RegistrySvcImageSpec;
    /**
    * The User Svc slug of the service whose instance is being registered.
    */
    'serviceSlug': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "apiSpecs",
            "baseName": "apiSpecs",
            "type": "Array<RegistrySvcAPISpec>"
        },
        {
            "name": "clients",
            "baseName": "clients",
            "type": "Array<RegistrySvcClient>"
        },
        {
            "name": "image",
            "baseName": "image",
            "type": "RegistrySvcImageSpec"
        },
        {
            "name": "serviceSlug",
            "baseName": "serviceSlug",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RegistrySvcServiceDefinition.attributeTypeMap;
    }
}

