/**
 * Superplatform
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RegistrySvcServiceDefinition } from './registrySvcServiceDefinition';

export class RegistrySvcSaveServiceDefinitionRequest {
    'serviceDefinition'?: RegistrySvcServiceDefinition;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "serviceDefinition",
            "baseName": "serviceDefinition",
            "type": "RegistrySvcServiceDefinition"
        }    ];

    static getAttributeTypeMap() {
        return RegistrySvcSaveServiceDefinitionRequest.attributeTypeMap;
    }
}

