/*
Singulatron

AI management and development platform.

API version: 0.2
Contact: sales@singulatron.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the NodeSvcGPU type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NodeSvcGPU{}

// NodeSvcGPU struct for NodeSvcGPU
type NodeSvcGPU struct {
	BusId *string `json:"busId,omitempty"`
	ComputeMode *string `json:"computeMode,omitempty"`
	GpuUtilization *float32 `json:"gpuUtilization,omitempty"`
	// Id Node.Hostname + IntraNodeId
	Id *string `json:"id,omitempty"`
	IntraNodeId *int32 `json:"intraNodeId,omitempty"`
	MemoryTotal *int32 `json:"memoryTotal,omitempty"`
	MemoryUsage *int32 `json:"memoryUsage,omitempty"`
	Name *string `json:"name,omitempty"`
	PerformanceState *string `json:"performanceState,omitempty"`
	PowerCap *float32 `json:"powerCap,omitempty"`
	PowerUsage *float32 `json:"powerUsage,omitempty"`
	ProcessDetails []NodeSvcProcess `json:"processDetails,omitempty"`
	Temperature *float32 `json:"temperature,omitempty"`
}

// NewNodeSvcGPU instantiates a new NodeSvcGPU object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodeSvcGPU() *NodeSvcGPU {
	this := NodeSvcGPU{}
	return &this
}

// NewNodeSvcGPUWithDefaults instantiates a new NodeSvcGPU object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodeSvcGPUWithDefaults() *NodeSvcGPU {
	this := NodeSvcGPU{}
	return &this
}

// GetBusId returns the BusId field value if set, zero value otherwise.
func (o *NodeSvcGPU) GetBusId() string {
	if o == nil || IsNil(o.BusId) {
		var ret string
		return ret
	}
	return *o.BusId
}

// GetBusIdOk returns a tuple with the BusId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodeSvcGPU) GetBusIdOk() (*string, bool) {
	if o == nil || IsNil(o.BusId) {
		return nil, false
	}
	return o.BusId, true
}

// HasBusId returns a boolean if a field has been set.
func (o *NodeSvcGPU) HasBusId() bool {
	if o != nil && !IsNil(o.BusId) {
		return true
	}

	return false
}

// SetBusId gets a reference to the given string and assigns it to the BusId field.
func (o *NodeSvcGPU) SetBusId(v string) {
	o.BusId = &v
}

// GetComputeMode returns the ComputeMode field value if set, zero value otherwise.
func (o *NodeSvcGPU) GetComputeMode() string {
	if o == nil || IsNil(o.ComputeMode) {
		var ret string
		return ret
	}
	return *o.ComputeMode
}

// GetComputeModeOk returns a tuple with the ComputeMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodeSvcGPU) GetComputeModeOk() (*string, bool) {
	if o == nil || IsNil(o.ComputeMode) {
		return nil, false
	}
	return o.ComputeMode, true
}

// HasComputeMode returns a boolean if a field has been set.
func (o *NodeSvcGPU) HasComputeMode() bool {
	if o != nil && !IsNil(o.ComputeMode) {
		return true
	}

	return false
}

// SetComputeMode gets a reference to the given string and assigns it to the ComputeMode field.
func (o *NodeSvcGPU) SetComputeMode(v string) {
	o.ComputeMode = &v
}

// GetGpuUtilization returns the GpuUtilization field value if set, zero value otherwise.
func (o *NodeSvcGPU) GetGpuUtilization() float32 {
	if o == nil || IsNil(o.GpuUtilization) {
		var ret float32
		return ret
	}
	return *o.GpuUtilization
}

// GetGpuUtilizationOk returns a tuple with the GpuUtilization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodeSvcGPU) GetGpuUtilizationOk() (*float32, bool) {
	if o == nil || IsNil(o.GpuUtilization) {
		return nil, false
	}
	return o.GpuUtilization, true
}

// HasGpuUtilization returns a boolean if a field has been set.
func (o *NodeSvcGPU) HasGpuUtilization() bool {
	if o != nil && !IsNil(o.GpuUtilization) {
		return true
	}

	return false
}

// SetGpuUtilization gets a reference to the given float32 and assigns it to the GpuUtilization field.
func (o *NodeSvcGPU) SetGpuUtilization(v float32) {
	o.GpuUtilization = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *NodeSvcGPU) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodeSvcGPU) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *NodeSvcGPU) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *NodeSvcGPU) SetId(v string) {
	o.Id = &v
}

// GetIntraNodeId returns the IntraNodeId field value if set, zero value otherwise.
func (o *NodeSvcGPU) GetIntraNodeId() int32 {
	if o == nil || IsNil(o.IntraNodeId) {
		var ret int32
		return ret
	}
	return *o.IntraNodeId
}

// GetIntraNodeIdOk returns a tuple with the IntraNodeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodeSvcGPU) GetIntraNodeIdOk() (*int32, bool) {
	if o == nil || IsNil(o.IntraNodeId) {
		return nil, false
	}
	return o.IntraNodeId, true
}

// HasIntraNodeId returns a boolean if a field has been set.
func (o *NodeSvcGPU) HasIntraNodeId() bool {
	if o != nil && !IsNil(o.IntraNodeId) {
		return true
	}

	return false
}

// SetIntraNodeId gets a reference to the given int32 and assigns it to the IntraNodeId field.
func (o *NodeSvcGPU) SetIntraNodeId(v int32) {
	o.IntraNodeId = &v
}

// GetMemoryTotal returns the MemoryTotal field value if set, zero value otherwise.
func (o *NodeSvcGPU) GetMemoryTotal() int32 {
	if o == nil || IsNil(o.MemoryTotal) {
		var ret int32
		return ret
	}
	return *o.MemoryTotal
}

// GetMemoryTotalOk returns a tuple with the MemoryTotal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodeSvcGPU) GetMemoryTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.MemoryTotal) {
		return nil, false
	}
	return o.MemoryTotal, true
}

// HasMemoryTotal returns a boolean if a field has been set.
func (o *NodeSvcGPU) HasMemoryTotal() bool {
	if o != nil && !IsNil(o.MemoryTotal) {
		return true
	}

	return false
}

// SetMemoryTotal gets a reference to the given int32 and assigns it to the MemoryTotal field.
func (o *NodeSvcGPU) SetMemoryTotal(v int32) {
	o.MemoryTotal = &v
}

// GetMemoryUsage returns the MemoryUsage field value if set, zero value otherwise.
func (o *NodeSvcGPU) GetMemoryUsage() int32 {
	if o == nil || IsNil(o.MemoryUsage) {
		var ret int32
		return ret
	}
	return *o.MemoryUsage
}

// GetMemoryUsageOk returns a tuple with the MemoryUsage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodeSvcGPU) GetMemoryUsageOk() (*int32, bool) {
	if o == nil || IsNil(o.MemoryUsage) {
		return nil, false
	}
	return o.MemoryUsage, true
}

// HasMemoryUsage returns a boolean if a field has been set.
func (o *NodeSvcGPU) HasMemoryUsage() bool {
	if o != nil && !IsNil(o.MemoryUsage) {
		return true
	}

	return false
}

// SetMemoryUsage gets a reference to the given int32 and assigns it to the MemoryUsage field.
func (o *NodeSvcGPU) SetMemoryUsage(v int32) {
	o.MemoryUsage = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *NodeSvcGPU) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodeSvcGPU) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *NodeSvcGPU) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *NodeSvcGPU) SetName(v string) {
	o.Name = &v
}

// GetPerformanceState returns the PerformanceState field value if set, zero value otherwise.
func (o *NodeSvcGPU) GetPerformanceState() string {
	if o == nil || IsNil(o.PerformanceState) {
		var ret string
		return ret
	}
	return *o.PerformanceState
}

// GetPerformanceStateOk returns a tuple with the PerformanceState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodeSvcGPU) GetPerformanceStateOk() (*string, bool) {
	if o == nil || IsNil(o.PerformanceState) {
		return nil, false
	}
	return o.PerformanceState, true
}

// HasPerformanceState returns a boolean if a field has been set.
func (o *NodeSvcGPU) HasPerformanceState() bool {
	if o != nil && !IsNil(o.PerformanceState) {
		return true
	}

	return false
}

// SetPerformanceState gets a reference to the given string and assigns it to the PerformanceState field.
func (o *NodeSvcGPU) SetPerformanceState(v string) {
	o.PerformanceState = &v
}

// GetPowerCap returns the PowerCap field value if set, zero value otherwise.
func (o *NodeSvcGPU) GetPowerCap() float32 {
	if o == nil || IsNil(o.PowerCap) {
		var ret float32
		return ret
	}
	return *o.PowerCap
}

// GetPowerCapOk returns a tuple with the PowerCap field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodeSvcGPU) GetPowerCapOk() (*float32, bool) {
	if o == nil || IsNil(o.PowerCap) {
		return nil, false
	}
	return o.PowerCap, true
}

// HasPowerCap returns a boolean if a field has been set.
func (o *NodeSvcGPU) HasPowerCap() bool {
	if o != nil && !IsNil(o.PowerCap) {
		return true
	}

	return false
}

// SetPowerCap gets a reference to the given float32 and assigns it to the PowerCap field.
func (o *NodeSvcGPU) SetPowerCap(v float32) {
	o.PowerCap = &v
}

// GetPowerUsage returns the PowerUsage field value if set, zero value otherwise.
func (o *NodeSvcGPU) GetPowerUsage() float32 {
	if o == nil || IsNil(o.PowerUsage) {
		var ret float32
		return ret
	}
	return *o.PowerUsage
}

// GetPowerUsageOk returns a tuple with the PowerUsage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodeSvcGPU) GetPowerUsageOk() (*float32, bool) {
	if o == nil || IsNil(o.PowerUsage) {
		return nil, false
	}
	return o.PowerUsage, true
}

// HasPowerUsage returns a boolean if a field has been set.
func (o *NodeSvcGPU) HasPowerUsage() bool {
	if o != nil && !IsNil(o.PowerUsage) {
		return true
	}

	return false
}

// SetPowerUsage gets a reference to the given float32 and assigns it to the PowerUsage field.
func (o *NodeSvcGPU) SetPowerUsage(v float32) {
	o.PowerUsage = &v
}

// GetProcessDetails returns the ProcessDetails field value if set, zero value otherwise.
func (o *NodeSvcGPU) GetProcessDetails() []NodeSvcProcess {
	if o == nil || IsNil(o.ProcessDetails) {
		var ret []NodeSvcProcess
		return ret
	}
	return o.ProcessDetails
}

// GetProcessDetailsOk returns a tuple with the ProcessDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodeSvcGPU) GetProcessDetailsOk() ([]NodeSvcProcess, bool) {
	if o == nil || IsNil(o.ProcessDetails) {
		return nil, false
	}
	return o.ProcessDetails, true
}

// HasProcessDetails returns a boolean if a field has been set.
func (o *NodeSvcGPU) HasProcessDetails() bool {
	if o != nil && !IsNil(o.ProcessDetails) {
		return true
	}

	return false
}

// SetProcessDetails gets a reference to the given []NodeSvcProcess and assigns it to the ProcessDetails field.
func (o *NodeSvcGPU) SetProcessDetails(v []NodeSvcProcess) {
	o.ProcessDetails = v
}

// GetTemperature returns the Temperature field value if set, zero value otherwise.
func (o *NodeSvcGPU) GetTemperature() float32 {
	if o == nil || IsNil(o.Temperature) {
		var ret float32
		return ret
	}
	return *o.Temperature
}

// GetTemperatureOk returns a tuple with the Temperature field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodeSvcGPU) GetTemperatureOk() (*float32, bool) {
	if o == nil || IsNil(o.Temperature) {
		return nil, false
	}
	return o.Temperature, true
}

// HasTemperature returns a boolean if a field has been set.
func (o *NodeSvcGPU) HasTemperature() bool {
	if o != nil && !IsNil(o.Temperature) {
		return true
	}

	return false
}

// SetTemperature gets a reference to the given float32 and assigns it to the Temperature field.
func (o *NodeSvcGPU) SetTemperature(v float32) {
	o.Temperature = &v
}

func (o NodeSvcGPU) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NodeSvcGPU) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BusId) {
		toSerialize["busId"] = o.BusId
	}
	if !IsNil(o.ComputeMode) {
		toSerialize["computeMode"] = o.ComputeMode
	}
	if !IsNil(o.GpuUtilization) {
		toSerialize["gpuUtilization"] = o.GpuUtilization
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.IntraNodeId) {
		toSerialize["intraNodeId"] = o.IntraNodeId
	}
	if !IsNil(o.MemoryTotal) {
		toSerialize["memoryTotal"] = o.MemoryTotal
	}
	if !IsNil(o.MemoryUsage) {
		toSerialize["memoryUsage"] = o.MemoryUsage
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.PerformanceState) {
		toSerialize["performanceState"] = o.PerformanceState
	}
	if !IsNil(o.PowerCap) {
		toSerialize["powerCap"] = o.PowerCap
	}
	if !IsNil(o.PowerUsage) {
		toSerialize["powerUsage"] = o.PowerUsage
	}
	if !IsNil(o.ProcessDetails) {
		toSerialize["processDetails"] = o.ProcessDetails
	}
	if !IsNil(o.Temperature) {
		toSerialize["temperature"] = o.Temperature
	}
	return toSerialize, nil
}

type NullableNodeSvcGPU struct {
	value *NodeSvcGPU
	isSet bool
}

func (v NullableNodeSvcGPU) Get() *NodeSvcGPU {
	return v.value
}

func (v *NullableNodeSvcGPU) Set(val *NodeSvcGPU) {
	v.value = val
	v.isSet = true
}

func (v NullableNodeSvcGPU) IsSet() bool {
	return v.isSet
}

func (v *NullableNodeSvcGPU) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodeSvcGPU(val *NodeSvcGPU) *NullableNodeSvcGPU {
	return &NullableNodeSvcGPU{value: val, isSet: true}
}

func (v NullableNodeSvcGPU) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodeSvcGPU) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


