/*
Superplatform

On-premise AI platform and microservices ecosystem.

API version: 0.2
Contact: sales@singulatron.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DockerSvcLaunchContainerResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DockerSvcLaunchContainerResponse{}

// DockerSvcLaunchContainerResponse struct for DockerSvcLaunchContainerResponse
type DockerSvcLaunchContainerResponse struct {
	Info *DockerSvcLaunchInfo `json:"info,omitempty"`
}

// NewDockerSvcLaunchContainerResponse instantiates a new DockerSvcLaunchContainerResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDockerSvcLaunchContainerResponse() *DockerSvcLaunchContainerResponse {
	this := DockerSvcLaunchContainerResponse{}
	return &this
}

// NewDockerSvcLaunchContainerResponseWithDefaults instantiates a new DockerSvcLaunchContainerResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDockerSvcLaunchContainerResponseWithDefaults() *DockerSvcLaunchContainerResponse {
	this := DockerSvcLaunchContainerResponse{}
	return &this
}

// GetInfo returns the Info field value if set, zero value otherwise.
func (o *DockerSvcLaunchContainerResponse) GetInfo() DockerSvcLaunchInfo {
	if o == nil || IsNil(o.Info) {
		var ret DockerSvcLaunchInfo
		return ret
	}
	return *o.Info
}

// GetInfoOk returns a tuple with the Info field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DockerSvcLaunchContainerResponse) GetInfoOk() (*DockerSvcLaunchInfo, bool) {
	if o == nil || IsNil(o.Info) {
		return nil, false
	}
	return o.Info, true
}

// HasInfo returns a boolean if a field has been set.
func (o *DockerSvcLaunchContainerResponse) HasInfo() bool {
	if o != nil && !IsNil(o.Info) {
		return true
	}

	return false
}

// SetInfo gets a reference to the given DockerSvcLaunchInfo and assigns it to the Info field.
func (o *DockerSvcLaunchContainerResponse) SetInfo(v DockerSvcLaunchInfo) {
	o.Info = &v
}

func (o DockerSvcLaunchContainerResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DockerSvcLaunchContainerResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Info) {
		toSerialize["info"] = o.Info
	}
	return toSerialize, nil
}

type NullableDockerSvcLaunchContainerResponse struct {
	value *DockerSvcLaunchContainerResponse
	isSet bool
}

func (v NullableDockerSvcLaunchContainerResponse) Get() *DockerSvcLaunchContainerResponse {
	return v.value
}

func (v *NullableDockerSvcLaunchContainerResponse) Set(val *DockerSvcLaunchContainerResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDockerSvcLaunchContainerResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDockerSvcLaunchContainerResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDockerSvcLaunchContainerResponse(val *DockerSvcLaunchContainerResponse) *NullableDockerSvcLaunchContainerResponse {
	return &NullableDockerSvcLaunchContainerResponse{value: val, isSet: true}
}

func (v NullableDockerSvcLaunchContainerResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDockerSvcLaunchContainerResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


