/*
Superplatform

On-premise AI platform and microservices ecosystem.

API version: 0.2
Contact: sales@singulatron.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DynamicSvcCreateObjectResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DynamicSvcCreateObjectResponse{}

// DynamicSvcCreateObjectResponse struct for DynamicSvcCreateObjectResponse
type DynamicSvcCreateObjectResponse struct {
	Object *DynamicSvcObject `json:"object,omitempty"`
}

// NewDynamicSvcCreateObjectResponse instantiates a new DynamicSvcCreateObjectResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDynamicSvcCreateObjectResponse() *DynamicSvcCreateObjectResponse {
	this := DynamicSvcCreateObjectResponse{}
	return &this
}

// NewDynamicSvcCreateObjectResponseWithDefaults instantiates a new DynamicSvcCreateObjectResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDynamicSvcCreateObjectResponseWithDefaults() *DynamicSvcCreateObjectResponse {
	this := DynamicSvcCreateObjectResponse{}
	return &this
}

// GetObject returns the Object field value if set, zero value otherwise.
func (o *DynamicSvcCreateObjectResponse) GetObject() DynamicSvcObject {
	if o == nil || IsNil(o.Object) {
		var ret DynamicSvcObject
		return ret
	}
	return *o.Object
}

// GetObjectOk returns a tuple with the Object field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DynamicSvcCreateObjectResponse) GetObjectOk() (*DynamicSvcObject, bool) {
	if o == nil || IsNil(o.Object) {
		return nil, false
	}
	return o.Object, true
}

// HasObject returns a boolean if a field has been set.
func (o *DynamicSvcCreateObjectResponse) HasObject() bool {
	if o != nil && !IsNil(o.Object) {
		return true
	}

	return false
}

// SetObject gets a reference to the given DynamicSvcObject and assigns it to the Object field.
func (o *DynamicSvcCreateObjectResponse) SetObject(v DynamicSvcObject) {
	o.Object = &v
}

func (o DynamicSvcCreateObjectResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DynamicSvcCreateObjectResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Object) {
		toSerialize["object"] = o.Object
	}
	return toSerialize, nil
}

type NullableDynamicSvcCreateObjectResponse struct {
	value *DynamicSvcCreateObjectResponse
	isSet bool
}

func (v NullableDynamicSvcCreateObjectResponse) Get() *DynamicSvcCreateObjectResponse {
	return v.value
}

func (v *NullableDynamicSvcCreateObjectResponse) Set(val *DynamicSvcCreateObjectResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDynamicSvcCreateObjectResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDynamicSvcCreateObjectResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDynamicSvcCreateObjectResponse(val *DynamicSvcCreateObjectResponse) *NullableDynamicSvcCreateObjectResponse {
	return &NullableDynamicSvcCreateObjectResponse{value: val, isSet: true}
}

func (v NullableDynamicSvcCreateObjectResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDynamicSvcCreateObjectResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


