/*
Singulatron

AI management and development platform.

API version: 0.2
Contact: sales@singulatron.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GenericSvcGenericObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GenericSvcGenericObject{}

// GenericSvcGenericObject struct for GenericSvcGenericObject
type GenericSvcGenericObject struct {
	CreatedAt *string `json:"createdAt,omitempty"`
	Data map[string]interface{} `json:"data"`
	Id *string `json:"id,omitempty"`
	// Public determines if the object is visible to all users. When it's false the entry is only visible to the user who created it. When it's true the entry is visible to everyone.
	Public *bool `json:"public,omitempty"`
	Table string `json:"table"`
	UpdatedAt *string `json:"updatedAt,omitempty"`
	UserId *string `json:"userId,omitempty"`
}

type _GenericSvcGenericObject GenericSvcGenericObject

// NewGenericSvcGenericObject instantiates a new GenericSvcGenericObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGenericSvcGenericObject(data map[string]interface{}, table string) *GenericSvcGenericObject {
	this := GenericSvcGenericObject{}
	this.Data = data
	this.Table = table
	return &this
}

// NewGenericSvcGenericObjectWithDefaults instantiates a new GenericSvcGenericObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGenericSvcGenericObjectWithDefaults() *GenericSvcGenericObject {
	this := GenericSvcGenericObject{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *GenericSvcGenericObject) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenericSvcGenericObject) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *GenericSvcGenericObject) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *GenericSvcGenericObject) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetData returns the Data field value
func (o *GenericSvcGenericObject) GetData() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GenericSvcGenericObject) GetDataOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *GenericSvcGenericObject) SetData(v map[string]interface{}) {
	o.Data = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GenericSvcGenericObject) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenericSvcGenericObject) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GenericSvcGenericObject) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GenericSvcGenericObject) SetId(v string) {
	o.Id = &v
}

// GetPublic returns the Public field value if set, zero value otherwise.
func (o *GenericSvcGenericObject) GetPublic() bool {
	if o == nil || IsNil(o.Public) {
		var ret bool
		return ret
	}
	return *o.Public
}

// GetPublicOk returns a tuple with the Public field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenericSvcGenericObject) GetPublicOk() (*bool, bool) {
	if o == nil || IsNil(o.Public) {
		return nil, false
	}
	return o.Public, true
}

// HasPublic returns a boolean if a field has been set.
func (o *GenericSvcGenericObject) HasPublic() bool {
	if o != nil && !IsNil(o.Public) {
		return true
	}

	return false
}

// SetPublic gets a reference to the given bool and assigns it to the Public field.
func (o *GenericSvcGenericObject) SetPublic(v bool) {
	o.Public = &v
}

// GetTable returns the Table field value
func (o *GenericSvcGenericObject) GetTable() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Table
}

// GetTableOk returns a tuple with the Table field value
// and a boolean to check if the value has been set.
func (o *GenericSvcGenericObject) GetTableOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Table, true
}

// SetTable sets field value
func (o *GenericSvcGenericObject) SetTable(v string) {
	o.Table = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *GenericSvcGenericObject) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenericSvcGenericObject) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *GenericSvcGenericObject) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *GenericSvcGenericObject) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *GenericSvcGenericObject) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenericSvcGenericObject) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *GenericSvcGenericObject) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *GenericSvcGenericObject) SetUserId(v string) {
	o.UserId = &v
}

func (o GenericSvcGenericObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GenericSvcGenericObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	toSerialize["data"] = o.Data
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Public) {
		toSerialize["public"] = o.Public
	}
	toSerialize["table"] = o.Table
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if !IsNil(o.UserId) {
		toSerialize["userId"] = o.UserId
	}
	return toSerialize, nil
}

func (o *GenericSvcGenericObject) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"table",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGenericSvcGenericObject := _GenericSvcGenericObject{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGenericSvcGenericObject)

	if err != nil {
		return err
	}

	*o = GenericSvcGenericObject(varGenericSvcGenericObject)

	return err
}

type NullableGenericSvcGenericObject struct {
	value *GenericSvcGenericObject
	isSet bool
}

func (v NullableGenericSvcGenericObject) Get() *GenericSvcGenericObject {
	return v.value
}

func (v *NullableGenericSvcGenericObject) Set(val *GenericSvcGenericObject) {
	v.value = val
	v.isSet = true
}

func (v NullableGenericSvcGenericObject) IsSet() bool {
	return v.isSet
}

func (v *NullableGenericSvcGenericObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGenericSvcGenericObject(val *GenericSvcGenericObject) *NullableGenericSvcGenericObject {
	return &NullableGenericSvcGenericObject{value: val, isSet: true}
}

func (v NullableGenericSvcGenericObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGenericSvcGenericObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


