/*
Singulatron

AI management and development platform.

API version: 0.2
Contact: sales@singulatron.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GenericSvcUpsertObjectResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GenericSvcUpsertObjectResponse{}

// GenericSvcUpsertObjectResponse struct for GenericSvcUpsertObjectResponse
type GenericSvcUpsertObjectResponse struct {
	Object *GenericSvcGenericObject `json:"object,omitempty"`
}

// NewGenericSvcUpsertObjectResponse instantiates a new GenericSvcUpsertObjectResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGenericSvcUpsertObjectResponse() *GenericSvcUpsertObjectResponse {
	this := GenericSvcUpsertObjectResponse{}
	return &this
}

// NewGenericSvcUpsertObjectResponseWithDefaults instantiates a new GenericSvcUpsertObjectResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGenericSvcUpsertObjectResponseWithDefaults() *GenericSvcUpsertObjectResponse {
	this := GenericSvcUpsertObjectResponse{}
	return &this
}

// GetObject returns the Object field value if set, zero value otherwise.
func (o *GenericSvcUpsertObjectResponse) GetObject() GenericSvcGenericObject {
	if o == nil || IsNil(o.Object) {
		var ret GenericSvcGenericObject
		return ret
	}
	return *o.Object
}

// GetObjectOk returns a tuple with the Object field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenericSvcUpsertObjectResponse) GetObjectOk() (*GenericSvcGenericObject, bool) {
	if o == nil || IsNil(o.Object) {
		return nil, false
	}
	return o.Object, true
}

// HasObject returns a boolean if a field has been set.
func (o *GenericSvcUpsertObjectResponse) HasObject() bool {
	if o != nil && !IsNil(o.Object) {
		return true
	}

	return false
}

// SetObject gets a reference to the given GenericSvcGenericObject and assigns it to the Object field.
func (o *GenericSvcUpsertObjectResponse) SetObject(v GenericSvcGenericObject) {
	o.Object = &v
}

func (o GenericSvcUpsertObjectResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GenericSvcUpsertObjectResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Object) {
		toSerialize["object"] = o.Object
	}
	return toSerialize, nil
}

type NullableGenericSvcUpsertObjectResponse struct {
	value *GenericSvcUpsertObjectResponse
	isSet bool
}

func (v NullableGenericSvcUpsertObjectResponse) Get() *GenericSvcUpsertObjectResponse {
	return v.value
}

func (v *NullableGenericSvcUpsertObjectResponse) Set(val *GenericSvcUpsertObjectResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGenericSvcUpsertObjectResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGenericSvcUpsertObjectResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGenericSvcUpsertObjectResponse(val *GenericSvcUpsertObjectResponse) *NullableGenericSvcUpsertObjectResponse {
	return &NullableGenericSvcUpsertObjectResponse{value: val, isSet: true}
}

func (v NullableGenericSvcUpsertObjectResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGenericSvcUpsertObjectResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


