/* tslint:disable */
/* eslint-disable */
/**
 * Superplatform
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatSvcMessage } from './ChatSvcMessage';
import {
    ChatSvcMessageFromJSON,
    ChatSvcMessageFromJSONTyped,
    ChatSvcMessageToJSON,
} from './ChatSvcMessage';
import type { ChatSvcAsset } from './ChatSvcAsset';
import {
    ChatSvcAssetFromJSON,
    ChatSvcAssetFromJSONTyped,
    ChatSvcAssetToJSON,
} from './ChatSvcAsset';

/**
 * 
 * @export
 * @interface ChatSvcGetMessagesResponse
 */
export interface ChatSvcGetMessagesResponse {
    /**
     * 
     * @type {Array<ChatSvcAsset>}
     * @memberof ChatSvcGetMessagesResponse
     */
    assets?: Array<ChatSvcAsset>;
    /**
     * 
     * @type {Array<ChatSvcMessage>}
     * @memberof ChatSvcGetMessagesResponse
     */
    messages?: Array<ChatSvcMessage>;
}

/**
 * Check if a given object implements the ChatSvcGetMessagesResponse interface.
 */
export function instanceOfChatSvcGetMessagesResponse(value: object): value is ChatSvcGetMessagesResponse {
    return true;
}

export function ChatSvcGetMessagesResponseFromJSON(json: any): ChatSvcGetMessagesResponse {
    return ChatSvcGetMessagesResponseFromJSONTyped(json, false);
}

export function ChatSvcGetMessagesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatSvcGetMessagesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'assets': json['assets'] == null ? undefined : ((json['assets'] as Array<any>).map(ChatSvcAssetFromJSON)),
        'messages': json['messages'] == null ? undefined : ((json['messages'] as Array<any>).map(ChatSvcMessageFromJSON)),
    };
}

export function ChatSvcGetMessagesResponseToJSON(value?: ChatSvcGetMessagesResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'assets': value['assets'] == null ? undefined : ((value['assets'] as Array<any>).map(ChatSvcAssetToJSON)),
        'messages': value['messages'] == null ? undefined : ((value['messages'] as Array<any>).map(ChatSvcMessageToJSON)),
    };
}

