/* tslint:disable */
/* eslint-disable */
/**
 * Superplatform
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatSvcEventMessageAdded
 */
export interface ChatSvcEventMessageAdded {
    /**
     * 
     * @type {string}
     * @memberof ChatSvcEventMessageAdded
     */
    threadId?: string;
}

/**
 * Check if a given object implements the ChatSvcEventMessageAdded interface.
 */
export function instanceOfChatSvcEventMessageAdded(value: object): value is ChatSvcEventMessageAdded {
    return true;
}

export function ChatSvcEventMessageAddedFromJSON(json: any): ChatSvcEventMessageAdded {
    return ChatSvcEventMessageAddedFromJSONTyped(json, false);
}

export function ChatSvcEventMessageAddedFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatSvcEventMessageAdded {
    if (json == null) {
        return json;
    }
    return {
        
        'threadId': json['threadId'] == null ? undefined : json['threadId'],
    };
}

export function ChatSvcEventMessageAddedToJSON(value?: ChatSvcEventMessageAdded | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'threadId': value['threadId'],
    };
}

