/* tslint:disable */
/* eslint-disable */
/**
 * Singulatron
 * Run and develop self-hosted AI apps. Your programmable in-house GPT. The Firebase for the AI age.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChattypesMessage
 */
export interface ChattypesMessage {
    /**
     * AssetIds defines the attachments the message has.
     * @type {Array<string>}
     * @memberof ChattypesMessage
     */
    assetIds?: Array<string>;
    /**
     * Content of the message eg. "Hi, what's up?"
     * @type {string}
     * @memberof ChattypesMessage
     */
    content?: string;
    /**
     * 
     * @type {string}
     * @memberof ChattypesMessage
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ChattypesMessage
     */
    id?: string;
    /**
     * ThreadId of the message.
     * @type {string}
     * @memberof ChattypesMessage
     */
    threadId?: string;
    /**
     * 
     * @type {string}
     * @memberof ChattypesMessage
     */
    updatedAt?: string;
    /**
     * UserId is the id of the user who wrote the message.
     * For AI messages this field is empty.
     * @type {string}
     * @memberof ChattypesMessage
     */
    userId?: string;
}

/**
 * Check if a given object implements the ChattypesMessage interface.
 */
export function instanceOfChattypesMessage(value: object): value is ChattypesMessage {
    return true;
}

export function ChattypesMessageFromJSON(json: any): ChattypesMessage {
    return ChattypesMessageFromJSONTyped(json, false);
}

export function ChattypesMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChattypesMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'assetIds': json['assetIds'] == null ? undefined : json['assetIds'],
        'content': json['content'] == null ? undefined : json['content'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'id': json['id'] == null ? undefined : json['id'],
        'threadId': json['threadId'] == null ? undefined : json['threadId'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function ChattypesMessageToJSON(value?: ChattypesMessage | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'assetIds': value['assetIds'],
        'content': value['content'],
        'createdAt': value['createdAt'],
        'id': value['id'],
        'threadId': value['threadId'],
        'updatedAt': value['updatedAt'],
        'userId': value['userId'],
    };
}

