/* tslint:disable */
/* eslint-disable */
/**
 * Superplatform
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatSvcEventThreadAdded
 */
export interface ChatSvcEventThreadAdded {
    /**
     * 
     * @type {string}
     * @memberof ChatSvcEventThreadAdded
     */
    threadId?: string;
}

/**
 * Check if a given object implements the ChatSvcEventThreadAdded interface.
 */
export function instanceOfChatSvcEventThreadAdded(value: object): value is ChatSvcEventThreadAdded {
    return true;
}

export function ChatSvcEventThreadAddedFromJSON(json: any): ChatSvcEventThreadAdded {
    return ChatSvcEventThreadAddedFromJSONTyped(json, false);
}

export function ChatSvcEventThreadAddedFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatSvcEventThreadAdded {
    if (json == null) {
        return json;
    }
    return {
        
        'threadId': json['threadId'] == null ? undefined : json['threadId'],
    };
}

export function ChatSvcEventThreadAddedToJSON(value?: ChatSvcEventThreadAdded | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'threadId': value['threadId'],
    };
}

