/* tslint:disable */
/* eslint-disable */
/**
 * Singulatron
 * Run and develop self-hosted AI apps. Your programmable in-house GPT. The Firebase for the AI age.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChattypesThread } from './ChattypesThread';
import {
    ChattypesThreadFromJSON,
    ChattypesThreadFromJSONTyped,
    ChattypesThreadToJSON,
} from './ChattypesThread';

/**
 * 
 * @export
 * @interface ChattypesGetThreadsResponse
 */
export interface ChattypesGetThreadsResponse {
    /**
     * 
     * @type {Array<ChattypesThread>}
     * @memberof ChattypesGetThreadsResponse
     */
    threads?: Array<ChattypesThread>;
}

/**
 * Check if a given object implements the ChattypesGetThreadsResponse interface.
 */
export function instanceOfChattypesGetThreadsResponse(value: object): value is ChattypesGetThreadsResponse {
    return true;
}

export function ChattypesGetThreadsResponseFromJSON(json: any): ChattypesGetThreadsResponse {
    return ChattypesGetThreadsResponseFromJSONTyped(json, false);
}

export function ChattypesGetThreadsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChattypesGetThreadsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'threads': json['threads'] == null ? undefined : ((json['threads'] as Array<any>).map(ChattypesThreadFromJSON)),
    };
}

export function ChattypesGetThreadsResponseToJSON(value?: ChattypesGetThreadsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'threads': value['threads'] == null ? undefined : ((value['threads'] as Array<any>).map(ChattypesThreadToJSON)),
    };
}

