/* tslint:disable */
/* eslint-disable */
/**
 * Singulatron
 * Run and develop self-hosted AI apps. Your programmable in-house GPT. The Firebase for the AI age.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChattypesMessage } from './ChattypesMessage';
import {
    ChattypesMessageFromJSON,
    ChattypesMessageFromJSONTyped,
    ChattypesMessageToJSON,
} from './ChattypesMessage';

/**
 * 
 * @export
 * @interface ChattypesAddMessageRequest
 */
export interface ChattypesAddMessageRequest {
    /**
     * 
     * @type {ChattypesMessage}
     * @memberof ChattypesAddMessageRequest
     */
    message?: ChattypesMessage;
}

/**
 * Check if a given object implements the ChattypesAddMessageRequest interface.
 */
export function instanceOfChattypesAddMessageRequest(value: object): value is ChattypesAddMessageRequest {
    return true;
}

export function ChattypesAddMessageRequestFromJSON(json: any): ChattypesAddMessageRequest {
    return ChattypesAddMessageRequestFromJSONTyped(json, false);
}

export function ChattypesAddMessageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChattypesAddMessageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : ChattypesMessageFromJSON(json['message']),
    };
}

export function ChattypesAddMessageRequestToJSON(value?: ChattypesAddMessageRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': ChattypesMessageToJSON(value['message']),
    };
}

