/* tslint:disable */
/* eslint-disable */
/**
 * Singulatron
 * Run and develop self-hosted AI apps. Your programmable in-house GPT. The Firebase for the AI age.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigtypesAppServiceConfig
 */
export interface ConfigtypesAppServiceConfig {
    /**
     * 
     * @type {boolean}
     * @memberof ConfigtypesAppServiceConfig
     */
    loggingDisabled?: boolean;
}

/**
 * Check if a given object implements the ConfigtypesAppServiceConfig interface.
 */
export function instanceOfConfigtypesAppServiceConfig(value: object): value is ConfigtypesAppServiceConfig {
    return true;
}

export function ConfigtypesAppServiceConfigFromJSON(json: any): ConfigtypesAppServiceConfig {
    return ConfigtypesAppServiceConfigFromJSONTyped(json, false);
}

export function ConfigtypesAppServiceConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigtypesAppServiceConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'loggingDisabled': json['loggingDisabled'] == null ? undefined : json['loggingDisabled'],
    };
}

export function ConfigtypesAppServiceConfigToJSON(value?: ConfigtypesAppServiceConfig | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'loggingDisabled': value['loggingDisabled'],
    };
}

