/* tslint:disable */
/* eslint-disable */
/**
 * Singulatron
 * Run and develop self-hosted AI apps. Your programmable in-house GPT. The Firebase for the AI age.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigtypesModelServiceConfig } from './ConfigtypesModelServiceConfig';
import {
    ConfigtypesModelServiceConfigFromJSON,
    ConfigtypesModelServiceConfigFromJSONTyped,
    ConfigtypesModelServiceConfigToJSON,
} from './ConfigtypesModelServiceConfig';
import type { ConfigtypesDownloadServiceConfig } from './ConfigtypesDownloadServiceConfig';
import {
    ConfigtypesDownloadServiceConfigFromJSON,
    ConfigtypesDownloadServiceConfigFromJSONTyped,
    ConfigtypesDownloadServiceConfigToJSON,
} from './ConfigtypesDownloadServiceConfig';
import type { ConfigtypesAppServiceConfig } from './ConfigtypesAppServiceConfig';
import {
    ConfigtypesAppServiceConfigFromJSON,
    ConfigtypesAppServiceConfigFromJSONTyped,
    ConfigtypesAppServiceConfigToJSON,
} from './ConfigtypesAppServiceConfig';

/**
 * 
 * @export
 * @interface ConfigtypesConfig
 */
export interface ConfigtypesConfig {
    /**
     * 
     * @type {ConfigtypesAppServiceConfig}
     * @memberof ConfigtypesConfig
     */
    app?: ConfigtypesAppServiceConfig;
    /**
     * 
     * @type {string}
     * @memberof ConfigtypesConfig
     */
    directory?: string;
    /**
     * 
     * @type {ConfigtypesDownloadServiceConfig}
     * @memberof ConfigtypesConfig
     */
    download?: ConfigtypesDownloadServiceConfig;
    /**
     * * This flag drives a minor UX feature:
     * 	 * if the user has not installed the runtime we show an INSTALL
     * 	 * button, but if the user has already installed the runtime we show
     * 	 * we show a START runtime button.
     * 	 *
     * @type {boolean}
     * @memberof ConfigtypesConfig
     */
    isRuntimeInstalled?: boolean;
    /**
     * 
     * @type {ConfigtypesModelServiceConfig}
     * @memberof ConfigtypesConfig
     */
    model?: ConfigtypesModelServiceConfig;
}

/**
 * Check if a given object implements the ConfigtypesConfig interface.
 */
export function instanceOfConfigtypesConfig(value: object): value is ConfigtypesConfig {
    return true;
}

export function ConfigtypesConfigFromJSON(json: any): ConfigtypesConfig {
    return ConfigtypesConfigFromJSONTyped(json, false);
}

export function ConfigtypesConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigtypesConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'app': json['app'] == null ? undefined : ConfigtypesAppServiceConfigFromJSON(json['app']),
        'directory': json['directory'] == null ? undefined : json['directory'],
        'download': json['download'] == null ? undefined : ConfigtypesDownloadServiceConfigFromJSON(json['download']),
        'isRuntimeInstalled': json['isRuntimeInstalled'] == null ? undefined : json['isRuntimeInstalled'],
        'model': json['model'] == null ? undefined : ConfigtypesModelServiceConfigFromJSON(json['model']),
    };
}

export function ConfigtypesConfigToJSON(value?: ConfigtypesConfig | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'app': ConfigtypesAppServiceConfigToJSON(value['app']),
        'directory': value['directory'],
        'download': ConfigtypesDownloadServiceConfigToJSON(value['download']),
        'isRuntimeInstalled': value['isRuntimeInstalled'],
        'model': ConfigtypesModelServiceConfigToJSON(value['model']),
    };
}

