/* tslint:disable */
/* eslint-disable */
/**
 * Superplatform
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeploySvcErrorResponse
 */
export interface DeploySvcErrorResponse {
    /**
     * 
     * @type {string}
     * @memberof DeploySvcErrorResponse
     */
    error?: string;
}

/**
 * Check if a given object implements the DeploySvcErrorResponse interface.
 */
export function instanceOfDeploySvcErrorResponse(value: object): value is DeploySvcErrorResponse {
    return true;
}

export function DeploySvcErrorResponseFromJSON(json: any): DeploySvcErrorResponse {
    return DeploySvcErrorResponseFromJSONTyped(json, false);
}

export function DeploySvcErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeploySvcErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function DeploySvcErrorResponseToJSON(value?: DeploySvcErrorResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'error': value['error'],
    };
}

