/* tslint:disable */
/* eslint-disable */
/**
 * Superplatform
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DockerSvcDockerInfo } from './DockerSvcDockerInfo';
import {
    DockerSvcDockerInfoFromJSON,
    DockerSvcDockerInfoFromJSONTyped,
    DockerSvcDockerInfoToJSON,
} from './DockerSvcDockerInfo';

/**
 * 
 * @export
 * @interface DockerSvcGetInfoResponse
 */
export interface DockerSvcGetInfoResponse {
    /**
     * 
     * @type {DockerSvcDockerInfo}
     * @memberof DockerSvcGetInfoResponse
     */
    info?: DockerSvcDockerInfo;
}

/**
 * Check if a given object implements the DockerSvcGetInfoResponse interface.
 */
export function instanceOfDockerSvcGetInfoResponse(value: object): value is DockerSvcGetInfoResponse {
    return true;
}

export function DockerSvcGetInfoResponseFromJSON(json: any): DockerSvcGetInfoResponse {
    return DockerSvcGetInfoResponseFromJSONTyped(json, false);
}

export function DockerSvcGetInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DockerSvcGetInfoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'info': json['info'] == null ? undefined : DockerSvcDockerInfoFromJSON(json['info']),
    };
}

export function DockerSvcGetInfoResponseToJSON(value?: DockerSvcGetInfoResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'info': DockerSvcDockerInfoToJSON(value['info']),
    };
}

