/* tslint:disable */
/* eslint-disable */
/**
 * Singulatron
 * Run and develop self-hosted AI apps. Your programmable in-house GPT. The Firebase for the AI age.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DockertypesGetDockerHostResponse
 */
export interface DockertypesGetDockerHostResponse {
    /**
     * 
     * @type {string}
     * @memberof DockertypesGetDockerHostResponse
     */
    host?: string;
}

/**
 * Check if a given object implements the DockertypesGetDockerHostResponse interface.
 */
export function instanceOfDockertypesGetDockerHostResponse(value: object): value is DockertypesGetDockerHostResponse {
    return true;
}

export function DockertypesGetDockerHostResponseFromJSON(json: any): DockertypesGetDockerHostResponse {
    return DockertypesGetDockerHostResponseFromJSONTyped(json, false);
}

export function DockertypesGetDockerHostResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DockertypesGetDockerHostResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'host': json['host'] == null ? undefined : json['host'],
    };
}

export function DockertypesGetDockerHostResponseToJSON(value?: DockertypesGetDockerHostResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'host': value['host'],
    };
}

