/* tslint:disable */
/* eslint-disable */
/**
 * Superplatform
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DownloadSvcErrorResponse
 */
export interface DownloadSvcErrorResponse {
    /**
     * 
     * @type {string}
     * @memberof DownloadSvcErrorResponse
     */
    error?: string;
}

/**
 * Check if a given object implements the DownloadSvcErrorResponse interface.
 */
export function instanceOfDownloadSvcErrorResponse(value: object): value is DownloadSvcErrorResponse {
    return true;
}

export function DownloadSvcErrorResponseFromJSON(json: any): DownloadSvcErrorResponse {
    return DownloadSvcErrorResponseFromJSONTyped(json, false);
}

export function DownloadSvcErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DownloadSvcErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function DownloadSvcErrorResponseToJSON(value?: DownloadSvcErrorResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'error': value['error'],
    };
}

