/* tslint:disable */
/* eslint-disable */
/**
 * Superplatform
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DatastoreQuery } from './DatastoreQuery';
import {
    DatastoreQueryFromJSON,
    DatastoreQueryFromJSONTyped,
    DatastoreQueryToJSON,
} from './DatastoreQuery';

/**
 * 
 * @export
 * @interface DynamicSvcQueryRequest
 */
export interface DynamicSvcQueryRequest {
    /**
     * 
     * @type {DatastoreQuery}
     * @memberof DynamicSvcQueryRequest
     */
    query?: DatastoreQuery;
    /**
     * 
     * @type {Array<string>}
     * @memberof DynamicSvcQueryRequest
     */
    readers?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof DynamicSvcQueryRequest
     */
    table?: string;
}

/**
 * Check if a given object implements the DynamicSvcQueryRequest interface.
 */
export function instanceOfDynamicSvcQueryRequest(value: object): value is DynamicSvcQueryRequest {
    return true;
}

export function DynamicSvcQueryRequestFromJSON(json: any): DynamicSvcQueryRequest {
    return DynamicSvcQueryRequestFromJSONTyped(json, false);
}

export function DynamicSvcQueryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DynamicSvcQueryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'query': json['query'] == null ? undefined : DatastoreQueryFromJSON(json['query']),
        'readers': json['readers'] == null ? undefined : json['readers'],
        'table': json['table'] == null ? undefined : json['table'],
    };
}

export function DynamicSvcQueryRequestToJSON(value?: DynamicSvcQueryRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'query': DatastoreQueryToJSON(value['query']),
        'readers': value['readers'],
        'table': value['table'],
    };
}

