/* tslint:disable */
/* eslint-disable */
/**
 * Singulatron
 * AI management and development platform.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DynamicSvcGenericObject } from './DynamicSvcGenericObject';
import {
    DynamicSvcGenericObjectFromJSON,
    DynamicSvcGenericObjectFromJSONTyped,
    DynamicSvcGenericObjectToJSON,
} from './DynamicSvcGenericObject';

/**
 * 
 * @export
 * @interface DynamicSvcUpsertObjectResponse
 */
export interface DynamicSvcUpsertObjectResponse {
    /**
     * 
     * @type {DynamicSvcGenericObject}
     * @memberof DynamicSvcUpsertObjectResponse
     */
    object?: DynamicSvcGenericObject;
}

/**
 * Check if a given object implements the DynamicSvcUpsertObjectResponse interface.
 */
export function instanceOfDynamicSvcUpsertObjectResponse(value: object): value is DynamicSvcUpsertObjectResponse {
    return true;
}

export function DynamicSvcUpsertObjectResponseFromJSON(json: any): DynamicSvcUpsertObjectResponse {
    return DynamicSvcUpsertObjectResponseFromJSONTyped(json, false);
}

export function DynamicSvcUpsertObjectResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DynamicSvcUpsertObjectResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'object': json['object'] == null ? undefined : DynamicSvcGenericObjectFromJSON(json['object']),
    };
}

export function DynamicSvcUpsertObjectResponseToJSON(value?: DynamicSvcUpsertObjectResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'object': DynamicSvcGenericObjectToJSON(value['object']),
    };
}

