/* tslint:disable */
/* eslint-disable */
/**
 * Singulatron
 * AI management and development platform.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DynamicSvcGenericObject
 */
export interface DynamicSvcGenericObject {
    /**
     * 
     * @type {string}
     * @memberof DynamicSvcGenericObject
     */
    createdAt?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof DynamicSvcGenericObject
     */
    data: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof DynamicSvcGenericObject
     */
    id?: string;
    /**
     * Public determines if the object is visible to all users.
     * When it's false the entry is only visible to the user who created it.
     * When it's true the entry is visible to everyone.
     * @type {boolean}
     * @memberof DynamicSvcGenericObject
     */
    _public?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DynamicSvcGenericObject
     */
    table: string;
    /**
     * 
     * @type {string}
     * @memberof DynamicSvcGenericObject
     */
    updatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof DynamicSvcGenericObject
     */
    userId?: string;
}

/**
 * Check if a given object implements the DynamicSvcGenericObject interface.
 */
export function instanceOfDynamicSvcGenericObject(value: object): value is DynamicSvcGenericObject {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('table' in value) || value['table'] === undefined) return false;
    return true;
}

export function DynamicSvcGenericObjectFromJSON(json: any): DynamicSvcGenericObject {
    return DynamicSvcGenericObjectFromJSONTyped(json, false);
}

export function DynamicSvcGenericObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): DynamicSvcGenericObject {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'data': json['data'],
        'id': json['id'] == null ? undefined : json['id'],
        '_public': json['public'] == null ? undefined : json['public'],
        'table': json['table'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function DynamicSvcGenericObjectToJSON(value?: DynamicSvcGenericObject | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'createdAt': value['createdAt'],
        'data': value['data'],
        'id': value['id'],
        'public': value['_public'],
        'table': value['table'],
        'updatedAt': value['updatedAt'],
        'userId': value['userId'],
    };
}

