/* tslint:disable */
/* eslint-disable */
/**
 * Singulatron
 * AI management and development platform.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DatastoreCondition } from './DatastoreCondition';
import {
    DatastoreConditionFromJSON,
    DatastoreConditionFromJSONTyped,
    DatastoreConditionToJSON,
} from './DatastoreCondition';

/**
 * 
 * @export
 * @interface DynamicSvcDeleteObjectRequest
 */
export interface DynamicSvcDeleteObjectRequest {
    /**
     * 
     * @type {Array<DatastoreCondition>}
     * @memberof DynamicSvcDeleteObjectRequest
     */
    conditions?: Array<DatastoreCondition>;
    /**
     * 
     * @type {string}
     * @memberof DynamicSvcDeleteObjectRequest
     */
    table?: string;
}

/**
 * Check if a given object implements the DynamicSvcDeleteObjectRequest interface.
 */
export function instanceOfDynamicSvcDeleteObjectRequest(value: object): value is DynamicSvcDeleteObjectRequest {
    return true;
}

export function DynamicSvcDeleteObjectRequestFromJSON(json: any): DynamicSvcDeleteObjectRequest {
    return DynamicSvcDeleteObjectRequestFromJSONTyped(json, false);
}

export function DynamicSvcDeleteObjectRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DynamicSvcDeleteObjectRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'conditions': json['conditions'] == null ? undefined : ((json['conditions'] as Array<any>).map(DatastoreConditionFromJSON)),
        'table': json['table'] == null ? undefined : json['table'],
    };
}

export function DynamicSvcDeleteObjectRequestToJSON(value?: DynamicSvcDeleteObjectRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'conditions': value['conditions'] == null ? undefined : ((value['conditions'] as Array<any>).map(DatastoreConditionToJSON)),
        'table': value['table'],
    };
}

