/* tslint:disable */
/* eslint-disable */
/**
 * Singulatron
 * Run and develop self-hosted AI apps. Your programmable in-house GPT. The Firebase for the AI age.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FirehosetypesErrorResponse
 */
export interface FirehosetypesErrorResponse {
    /**
     * 
     * @type {string}
     * @memberof FirehosetypesErrorResponse
     */
    error?: string;
}

/**
 * Check if a given object implements the FirehosetypesErrorResponse interface.
 */
export function instanceOfFirehosetypesErrorResponse(value: object): value is FirehosetypesErrorResponse {
    return true;
}

export function FirehosetypesErrorResponseFromJSON(json: any): FirehosetypesErrorResponse {
    return FirehosetypesErrorResponseFromJSONTyped(json, false);
}

export function FirehosetypesErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FirehosetypesErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function FirehosetypesErrorResponseToJSON(value?: FirehosetypesErrorResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'error': value['error'],
    };
}

