/* tslint:disable */
/* eslint-disable */
/**
 * Singulatron
 * Run and develop self-hosted AI apps. Your programmable in-house GPT. The Firebase for the AI age.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FirehosetypesEvent } from './FirehosetypesEvent';
import {
    FirehosetypesEventFromJSON,
    FirehosetypesEventFromJSONTyped,
    FirehosetypesEventToJSON,
} from './FirehosetypesEvent';

/**
 * 
 * @export
 * @interface FirehosetypesPublishRequest
 */
export interface FirehosetypesPublishRequest {
    /**
     * 
     * @type {FirehosetypesEvent}
     * @memberof FirehosetypesPublishRequest
     */
    event?: FirehosetypesEvent;
}

/**
 * Check if a given object implements the FirehosetypesPublishRequest interface.
 */
export function instanceOfFirehosetypesPublishRequest(value: object): value is FirehosetypesPublishRequest {
    return true;
}

export function FirehosetypesPublishRequestFromJSON(json: any): FirehosetypesPublishRequest {
    return FirehosetypesPublishRequestFromJSONTyped(json, false);
}

export function FirehosetypesPublishRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FirehosetypesPublishRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'event': json['event'] == null ? undefined : FirehosetypesEventFromJSON(json['event']),
    };
}

export function FirehosetypesPublishRequestToJSON(value?: FirehosetypesPublishRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'event': FirehosetypesEventToJSON(value['event']),
    };
}

