/* tslint:disable */
/* eslint-disable */
/**
 * Singulatron
 * Run and develop self-hosted AI apps. Your programmable in-house GPT. The Firebase for the AI age.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenerictypesGenericObject
 */
export interface GenerictypesGenericObject {
    /**
     * 
     * @type {string}
     * @memberof GenerictypesGenericObject
     */
    createdAt?: string;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof GenerictypesGenericObject
     */
    data: { [key: string]: object; };
    /**
     * 
     * @type {string}
     * @memberof GenerictypesGenericObject
     */
    id?: string;
    /**
     * Public determines if the object is visible to all users.
     * When it's false the entry is only visible to the user who created it.
     * When it's true the entry is visible to everyone.
     * @type {boolean}
     * @memberof GenerictypesGenericObject
     */
    _public?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GenerictypesGenericObject
     */
    table: string;
    /**
     * 
     * @type {string}
     * @memberof GenerictypesGenericObject
     */
    updatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof GenerictypesGenericObject
     */
    userId?: string;
}

/**
 * Check if a given object implements the GenerictypesGenericObject interface.
 */
export function instanceOfGenerictypesGenericObject(value: object): value is GenerictypesGenericObject {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('table' in value) || value['table'] === undefined) return false;
    return true;
}

export function GenerictypesGenericObjectFromJSON(json: any): GenerictypesGenericObject {
    return GenerictypesGenericObjectFromJSONTyped(json, false);
}

export function GenerictypesGenericObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerictypesGenericObject {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'data': json['data'],
        'id': json['id'] == null ? undefined : json['id'],
        '_public': json['public'] == null ? undefined : json['public'],
        'table': json['table'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function GenerictypesGenericObjectToJSON(value?: GenerictypesGenericObject | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'createdAt': value['createdAt'],
        'data': value['data'],
        'id': value['id'],
        'public': value['_public'],
        'table': value['table'],
        'updatedAt': value['updatedAt'],
        'userId': value['userId'],
    };
}

