/* tslint:disable */
/* eslint-disable */
/**
 * Singulatron
 * Run and develop self-hosted AI apps. Your programmable in-house GPT. The Firebase for the AI age.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DatastoreCondition } from './DatastoreCondition';
import {
    DatastoreConditionFromJSON,
    DatastoreConditionFromJSONTyped,
    DatastoreConditionToJSON,
} from './DatastoreCondition';

/**
 * 
 * @export
 * @interface GenericSvcDeleteObjectRequest
 */
export interface GenericSvcDeleteObjectRequest {
    /**
     * 
     * @type {Array<DatastoreCondition>}
     * @memberof GenericSvcDeleteObjectRequest
     */
    conditions?: Array<DatastoreCondition>;
    /**
     * 
     * @type {string}
     * @memberof GenericSvcDeleteObjectRequest
     */
    table?: string;
}

/**
 * Check if a given object implements the GenericSvcDeleteObjectRequest interface.
 */
export function instanceOfGenericSvcDeleteObjectRequest(value: object): value is GenericSvcDeleteObjectRequest {
    return true;
}

export function GenericSvcDeleteObjectRequestFromJSON(json: any): GenericSvcDeleteObjectRequest {
    return GenericSvcDeleteObjectRequestFromJSONTyped(json, false);
}

export function GenericSvcDeleteObjectRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenericSvcDeleteObjectRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'conditions': json['conditions'] == null ? undefined : ((json['conditions'] as Array<any>).map(DatastoreConditionFromJSON)),
        'table': json['table'] == null ? undefined : json['table'],
    };
}

export function GenericSvcDeleteObjectRequestToJSON(value?: GenericSvcDeleteObjectRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'conditions': value['conditions'] == null ? undefined : ((value['conditions'] as Array<any>).map(DatastoreConditionToJSON)),
        'table': value['table'],
    };
}

