/* tslint:disable */
/* eslint-disable */
/**
 * Singulatron
 * Run and develop self-hosted AI apps. Your programmable in-house GPT. The Firebase for the AI age.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenerictypesErrorResponse
 */
export interface GenerictypesErrorResponse {
    /**
     * 
     * @type {string}
     * @memberof GenerictypesErrorResponse
     */
    error?: string;
}

/**
 * Check if a given object implements the GenerictypesErrorResponse interface.
 */
export function instanceOfGenerictypesErrorResponse(value: object): value is GenerictypesErrorResponse {
    return true;
}

export function GenerictypesErrorResponseFromJSON(json: any): GenerictypesErrorResponse {
    return GenerictypesErrorResponseFromJSONTyped(json, false);
}

export function GenerictypesErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerictypesErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function GenerictypesErrorResponseToJSON(value?: GenerictypesErrorResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'error': value['error'],
    };
}

