/* tslint:disable */
/* eslint-disable */
/**
 * Singulatron
 * AI management and development platform.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DatastoreQuery } from './DatastoreQuery';
import {
    DatastoreQueryFromJSON,
    DatastoreQueryFromJSONTyped,
    DatastoreQueryToJSON,
} from './DatastoreQuery';

/**
 * 
 * @export
 * @interface GenericSvcQueryRequest
 */
export interface GenericSvcQueryRequest {
    /**
     * 
     * @type {boolean}
     * @memberof GenericSvcQueryRequest
     */
    _public?: boolean;
    /**
     * 
     * @type {DatastoreQuery}
     * @memberof GenericSvcQueryRequest
     */
    query?: DatastoreQuery;
    /**
     * 
     * @type {string}
     * @memberof GenericSvcQueryRequest
     */
    table?: string;
}

/**
 * Check if a given object implements the GenericSvcQueryRequest interface.
 */
export function instanceOfGenericSvcQueryRequest(value: object): value is GenericSvcQueryRequest {
    return true;
}

export function GenericSvcQueryRequestFromJSON(json: any): GenericSvcQueryRequest {
    return GenericSvcQueryRequestFromJSONTyped(json, false);
}

export function GenericSvcQueryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenericSvcQueryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        '_public': json['public'] == null ? undefined : json['public'],
        'query': json['query'] == null ? undefined : DatastoreQueryFromJSON(json['query']),
        'table': json['table'] == null ? undefined : json['table'],
    };
}

export function GenericSvcQueryRequestToJSON(value?: GenericSvcQueryRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'public': value['_public'],
        'query': DatastoreQueryToJSON(value['query']),
        'table': value['table'],
    };
}

