/* tslint:disable */
/* eslint-disable */
/**
 * Singulatron
 * Run and develop self-hosted AI apps. Your programmable in-house GPT. The Firebase for the AI age.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DatastoreCondition } from './DatastoreCondition';
import {
    DatastoreConditionFromJSON,
    DatastoreConditionFromJSONTyped,
    DatastoreConditionToJSON,
} from './DatastoreCondition';
import type { GenerictypesGenericObject } from './GenerictypesGenericObject';
import {
    GenerictypesGenericObjectFromJSON,
    GenerictypesGenericObjectFromJSONTyped,
    GenerictypesGenericObjectToJSON,
} from './GenerictypesGenericObject';

/**
 * 
 * @export
 * @interface GenerictypesUpdateRequest
 */
export interface GenerictypesUpdateRequest {
    /**
     * 
     * @type {Array<DatastoreCondition>}
     * @memberof GenerictypesUpdateRequest
     */
    conditions?: Array<DatastoreCondition>;
    /**
     * 
     * @type {GenerictypesGenericObject}
     * @memberof GenerictypesUpdateRequest
     */
    object?: GenerictypesGenericObject;
    /**
     * 
     * @type {string}
     * @memberof GenerictypesUpdateRequest
     */
    table?: string;
}

/**
 * Check if a given object implements the GenerictypesUpdateRequest interface.
 */
export function instanceOfGenerictypesUpdateRequest(value: object): value is GenerictypesUpdateRequest {
    return true;
}

export function GenerictypesUpdateRequestFromJSON(json: any): GenerictypesUpdateRequest {
    return GenerictypesUpdateRequestFromJSONTyped(json, false);
}

export function GenerictypesUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerictypesUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'conditions': json['conditions'] == null ? undefined : ((json['conditions'] as Array<any>).map(DatastoreConditionFromJSON)),
        'object': json['object'] == null ? undefined : GenerictypesGenericObjectFromJSON(json['object']),
        'table': json['table'] == null ? undefined : json['table'],
    };
}

export function GenerictypesUpdateRequestToJSON(value?: GenerictypesUpdateRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'conditions': value['conditions'] == null ? undefined : ((value['conditions'] as Array<any>).map(DatastoreConditionToJSON)),
        'object': GenerictypesGenericObjectToJSON(value['object']),
        'table': value['table'],
    };
}

