/* tslint:disable */
/* eslint-disable */
/**
 * Singulatron
 * Run and develop self-hosted AI apps. Your programmable in-house GPT. The Firebase for the AI age.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenericSvcErrorResponse
 */
export interface GenericSvcErrorResponse {
    /**
     * 
     * @type {string}
     * @memberof GenericSvcErrorResponse
     */
    error?: string;
}

/**
 * Check if a given object implements the GenericSvcErrorResponse interface.
 */
export function instanceOfGenericSvcErrorResponse(value: object): value is GenericSvcErrorResponse {
    return true;
}

export function GenericSvcErrorResponseFromJSON(json: any): GenericSvcErrorResponse {
    return GenericSvcErrorResponseFromJSONTyped(json, false);
}

export function GenericSvcErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenericSvcErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function GenericSvcErrorResponseToJSON(value?: GenericSvcErrorResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'error': value['error'],
    };
}

