/* tslint:disable */
/* eslint-disable */
/**
 * Singulatron
 * Run and develop self-hosted AI apps. Your programmable in-house GPT. The Firebase for the AI age.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GenericSvcGenericObjectCreateFields } from './GenericSvcGenericObjectCreateFields';
import {
    GenericSvcGenericObjectCreateFieldsFromJSON,
    GenericSvcGenericObjectCreateFieldsFromJSONTyped,
    GenericSvcGenericObjectCreateFieldsToJSON,
} from './GenericSvcGenericObjectCreateFields';

/**
 * 
 * @export
 * @interface GenericSvcCreateObjectRequest
 */
export interface GenericSvcCreateObjectRequest {
    /**
     * 
     * @type {GenericSvcGenericObjectCreateFields}
     * @memberof GenericSvcCreateObjectRequest
     */
    object?: GenericSvcGenericObjectCreateFields;
}

/**
 * Check if a given object implements the GenericSvcCreateObjectRequest interface.
 */
export function instanceOfGenericSvcCreateObjectRequest(value: object): value is GenericSvcCreateObjectRequest {
    return true;
}

export function GenericSvcCreateObjectRequestFromJSON(json: any): GenericSvcCreateObjectRequest {
    return GenericSvcCreateObjectRequestFromJSONTyped(json, false);
}

export function GenericSvcCreateObjectRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenericSvcCreateObjectRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'object': json['object'] == null ? undefined : GenericSvcGenericObjectCreateFieldsFromJSON(json['object']),
    };
}

export function GenericSvcCreateObjectRequestToJSON(value?: GenericSvcCreateObjectRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'object': GenericSvcGenericObjectCreateFieldsToJSON(value['object']),
    };
}

