/* tslint:disable */
/* eslint-disable */
/**
 * Singulatron
 * Run and develop self-hosted AI apps. Your programmable in-house GPT. The Firebase for the AI age.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModeltypesErrorResponse
 */
export interface ModeltypesErrorResponse {
    /**
     * 
     * @type {string}
     * @memberof ModeltypesErrorResponse
     */
    error?: string;
}

/**
 * Check if a given object implements the ModeltypesErrorResponse interface.
 */
export function instanceOfModeltypesErrorResponse(value: object): value is ModeltypesErrorResponse {
    return true;
}

export function ModeltypesErrorResponseFromJSON(json: any): ModeltypesErrorResponse {
    return ModeltypesErrorResponseFromJSONTyped(json, false);
}

export function ModeltypesErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModeltypesErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function ModeltypesErrorResponseToJSON(value?: ModeltypesErrorResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'error': value['error'],
    };
}

