/* tslint:disable */
/* eslint-disable */
/**
 * Superplatform
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelSvcModelStatus
 */
export interface ModelSvcModelStatus {
    /**
     * 
     * @type {string}
     * @memberof ModelSvcModelStatus
     */
    address?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModelSvcModelStatus
     */
    assetsReady?: boolean;
    /**
     * Running triggers onModelLaunch on the frontend.
     * 	Running is true when the model is both running and answering
     * 	- fully loaded.
     * @type {boolean}
     * @memberof ModelSvcModelStatus
     */
    running?: boolean;
}

/**
 * Check if a given object implements the ModelSvcModelStatus interface.
 */
export function instanceOfModelSvcModelStatus(value: object): value is ModelSvcModelStatus {
    return true;
}

export function ModelSvcModelStatusFromJSON(json: any): ModelSvcModelStatus {
    return ModelSvcModelStatusFromJSONTyped(json, false);
}

export function ModelSvcModelStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelSvcModelStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'] == null ? undefined : json['address'],
        'assetsReady': json['assetsReady'] == null ? undefined : json['assetsReady'],
        'running': json['running'] == null ? undefined : json['running'],
    };
}

export function ModelSvcModelStatusToJSON(value?: ModelSvcModelStatus | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'address': value['address'],
        'assetsReady': value['assetsReady'],
        'running': value['running'],
    };
}

