/* tslint:disable */
/* eslint-disable */
/**
 * Singulatron
 * AI management and development platform.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NodeSvcNode } from './NodeSvcNode';
import {
    NodeSvcNodeFromJSON,
    NodeSvcNodeFromJSONTyped,
    NodeSvcNodeToJSON,
} from './NodeSvcNode';

/**
 * 
 * @export
 * @interface NodeSvcListNodesResponse
 */
export interface NodeSvcListNodesResponse {
    /**
     * 
     * @type {Array<NodeSvcNode>}
     * @memberof NodeSvcListNodesResponse
     */
    nodes?: Array<NodeSvcNode>;
}

/**
 * Check if a given object implements the NodeSvcListNodesResponse interface.
 */
export function instanceOfNodeSvcListNodesResponse(value: object): value is NodeSvcListNodesResponse {
    return true;
}

export function NodeSvcListNodesResponseFromJSON(json: any): NodeSvcListNodesResponse {
    return NodeSvcListNodesResponseFromJSONTyped(json, false);
}

export function NodeSvcListNodesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeSvcListNodesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'nodes': json['nodes'] == null ? undefined : ((json['nodes'] as Array<any>).map(NodeSvcNodeFromJSON)),
    };
}

export function NodeSvcListNodesResponseToJSON(value?: NodeSvcListNodesResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'nodes': value['nodes'] == null ? undefined : ((value['nodes'] as Array<any>).map(NodeSvcNodeToJSON)),
    };
}

