/* tslint:disable */
/* eslint-disable */
/**
 * Singulatron
 * AI management and development platform.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NodeSvcProcess
 */
export interface NodeSvcProcess {
    /**
     * 
     * @type {number}
     * @memberof NodeSvcProcess
     */
    memoryUsage?: number;
    /**
     * 
     * @type {number}
     * @memberof NodeSvcProcess
     */
    pid?: number;
    /**
     * 
     * @type {string}
     * @memberof NodeSvcProcess
     */
    processName?: string;
}

/**
 * Check if a given object implements the NodeSvcProcess interface.
 */
export function instanceOfNodeSvcProcess(value: object): value is NodeSvcProcess {
    return true;
}

export function NodeSvcProcessFromJSON(json: any): NodeSvcProcess {
    return NodeSvcProcessFromJSONTyped(json, false);
}

export function NodeSvcProcessFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeSvcProcess {
    if (json == null) {
        return json;
    }
    return {
        
        'memoryUsage': json['memoryUsage'] == null ? undefined : json['memoryUsage'],
        'pid': json['pid'] == null ? undefined : json['pid'],
        'processName': json['processName'] == null ? undefined : json['processName'],
    };
}

export function NodeSvcProcessToJSON(value?: NodeSvcProcess | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'memoryUsage': value['memoryUsage'],
        'pid': value['pid'],
        'processName': value['processName'],
    };
}

