/* tslint:disable */
/* eslint-disable */
/**
 * Superplatform
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PromptSvcRemovePromptRequest
 */
export interface PromptSvcRemovePromptRequest {
    /**
     * 
     * @type {string}
     * @memberof PromptSvcRemovePromptRequest
     */
    promptId?: string;
}

/**
 * Check if a given object implements the PromptSvcRemovePromptRequest interface.
 */
export function instanceOfPromptSvcRemovePromptRequest(value: object): value is PromptSvcRemovePromptRequest {
    return true;
}

export function PromptSvcRemovePromptRequestFromJSON(json: any): PromptSvcRemovePromptRequest {
    return PromptSvcRemovePromptRequestFromJSONTyped(json, false);
}

export function PromptSvcRemovePromptRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromptSvcRemovePromptRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'promptId': json['promptId'] == null ? undefined : json['promptId'],
    };
}

export function PromptSvcRemovePromptRequestToJSON(value?: PromptSvcRemovePromptRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'promptId': value['promptId'],
    };
}

