/* tslint:disable */
/* eslint-disable */
/**
 * Singulatron
 * AI management and development platform.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegistrySvcServiceInstance
 */
export interface RegistrySvcServiceInstance {
    /**
     * Host of the service instance address. Required if URL is not provided
     * @type {string}
     * @memberof RegistrySvcServiceInstance
     */
    host?: string;
    /**
     * Required: ID of the service instance (e.g., "https://api.com:999/user-svc")
     * @type {string}
     * @memberof RegistrySvcServiceInstance
     */
    id?: string;
    /**
     * IP of the service instance address. Optional: to register by IP instead of host
     * @type {string}
     * @memberof RegistrySvcServiceInstance
     */
    ip?: string;
    /**
     * Path of the service instance address. Optional (e.g., "/api")
     * @type {string}
     * @memberof RegistrySvcServiceInstance
     */
    path?: string;
    /**
     * Port of the service instance address. Required if URL is not provided
     * @type {number}
     * @memberof RegistrySvcServiceInstance
     */
    port?: number;
    /**
     * Scheme of the service instance address. Required if URL is not provided
     * @type {string}
     * @memberof RegistrySvcServiceInstance
     */
    scheme?: string;
    /**
     * Required: slug of the service (e.g., "user-svc")
     * @type {string}
     * @memberof RegistrySvcServiceInstance
     */
    slug?: string;
    /**
     * Optional: full URL (e.g., "https://myserver.com:5981")
     * @type {string}
     * @memberof RegistrySvcServiceInstance
     */
    url?: string;
}

/**
 * Check if a given object implements the RegistrySvcServiceInstance interface.
 */
export function instanceOfRegistrySvcServiceInstance(value: object): value is RegistrySvcServiceInstance {
    return true;
}

export function RegistrySvcServiceInstanceFromJSON(json: any): RegistrySvcServiceInstance {
    return RegistrySvcServiceInstanceFromJSONTyped(json, false);
}

export function RegistrySvcServiceInstanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegistrySvcServiceInstance {
    if (json == null) {
        return json;
    }
    return {
        
        'host': json['host'] == null ? undefined : json['host'],
        'id': json['id'] == null ? undefined : json['id'],
        'ip': json['ip'] == null ? undefined : json['ip'],
        'path': json['path'] == null ? undefined : json['path'],
        'port': json['port'] == null ? undefined : json['port'],
        'scheme': json['scheme'] == null ? undefined : json['scheme'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function RegistrySvcServiceInstanceToJSON(value?: RegistrySvcServiceInstance | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'host': value['host'],
        'id': value['id'],
        'ip': value['ip'],
        'path': value['path'],
        'port': value['port'],
        'scheme': value['scheme'],
        'slug': value['slug'],
        'url': value['url'],
    };
}

