/* tslint:disable */
/* eslint-disable */
/**
 * Superplatform
 * AI management and development platform.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RegistrySvcServiceInstance } from './RegistrySvcServiceInstance';
import {
    RegistrySvcServiceInstanceFromJSON,
    RegistrySvcServiceInstanceFromJSONTyped,
    RegistrySvcServiceInstanceToJSON,
} from './RegistrySvcServiceInstance';

/**
 * 
 * @export
 * @interface RegistrySvcQueryServiceInstancesResponse
 */
export interface RegistrySvcQueryServiceInstancesResponse {
    /**
     * 
     * @type {Array<RegistrySvcServiceInstance>}
     * @memberof RegistrySvcQueryServiceInstancesResponse
     */
    instances?: Array<RegistrySvcServiceInstance>;
}

/**
 * Check if a given object implements the RegistrySvcQueryServiceInstancesResponse interface.
 */
export function instanceOfRegistrySvcQueryServiceInstancesResponse(value: object): value is RegistrySvcQueryServiceInstancesResponse {
    return true;
}

export function RegistrySvcQueryServiceInstancesResponseFromJSON(json: any): RegistrySvcQueryServiceInstancesResponse {
    return RegistrySvcQueryServiceInstancesResponseFromJSONTyped(json, false);
}

export function RegistrySvcQueryServiceInstancesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegistrySvcQueryServiceInstancesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'instances': json['instances'] == null ? undefined : ((json['instances'] as Array<any>).map(RegistrySvcServiceInstanceFromJSON)),
    };
}

export function RegistrySvcQueryServiceInstancesResponseToJSON(value?: RegistrySvcQueryServiceInstancesResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'instances': value['instances'] == null ? undefined : ((value['instances'] as Array<any>).map(RegistrySvcServiceInstanceToJSON)),
    };
}

