/* tslint:disable */
/* eslint-disable */
/**
 * Superplatform
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegistrySvcRegisterInstanceRequest
 */
export interface RegistrySvcRegisterInstanceRequest {
    /**
     * The service definition id.
     * @type {string}
     * @memberof RegistrySvcRegisterInstanceRequest
     */
    definitionId: string;
    /**
     * Host of the instance address. Required if URL is not provided
     * @type {string}
     * @memberof RegistrySvcRegisterInstanceRequest
     */
    host?: string;
    /**
     * IP of the instance address. Optional: to register by IP instead of host
     * @type {string}
     * @memberof RegistrySvcRegisterInstanceRequest
     */
    ip?: string;
    /**
     * Path of the instance address. Optional (e.g., "/api")
     * @type {string}
     * @memberof RegistrySvcRegisterInstanceRequest
     */
    path?: string;
    /**
     * Port of the instance address. Required if URL is not provided
     * @type {number}
     * @memberof RegistrySvcRegisterInstanceRequest
     */
    port?: number;
    /**
     * Scheme of the instance address. Required if URL is not provided.
     * @type {string}
     * @memberof RegistrySvcRegisterInstanceRequest
     */
    scheme?: string;
    /**
     * Full address URL of the instance.
     * @type {string}
     * @memberof RegistrySvcRegisterInstanceRequest
     */
    url?: string;
}

/**
 * Check if a given object implements the RegistrySvcRegisterInstanceRequest interface.
 */
export function instanceOfRegistrySvcRegisterInstanceRequest(value: object): value is RegistrySvcRegisterInstanceRequest {
    if (!('definitionId' in value) || value['definitionId'] === undefined) return false;
    return true;
}

export function RegistrySvcRegisterInstanceRequestFromJSON(json: any): RegistrySvcRegisterInstanceRequest {
    return RegistrySvcRegisterInstanceRequestFromJSONTyped(json, false);
}

export function RegistrySvcRegisterInstanceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegistrySvcRegisterInstanceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'definitionId': json['definitionId'],
        'host': json['host'] == null ? undefined : json['host'],
        'ip': json['ip'] == null ? undefined : json['ip'],
        'path': json['path'] == null ? undefined : json['path'],
        'port': json['port'] == null ? undefined : json['port'],
        'scheme': json['scheme'] == null ? undefined : json['scheme'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function RegistrySvcRegisterInstanceRequestToJSON(value?: RegistrySvcRegisterInstanceRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'definitionId': value['definitionId'],
        'host': value['host'],
        'ip': value['ip'],
        'path': value['path'],
        'port': value['port'],
        'scheme': value['scheme'],
        'url': value['url'],
    };
}

