/* tslint:disable */
/* eslint-disable */
/**
 * Superplatform
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RegistrySvcDefinition } from './RegistrySvcDefinition';
import {
    RegistrySvcDefinitionFromJSON,
    RegistrySvcDefinitionFromJSONTyped,
    RegistrySvcDefinitionToJSON,
} from './RegistrySvcDefinition';

/**
 * 
 * @export
 * @interface RegistrySvcListDefinitionsResponse
 */
export interface RegistrySvcListDefinitionsResponse {
    /**
     * 
     * @type {Array<RegistrySvcDefinition>}
     * @memberof RegistrySvcListDefinitionsResponse
     */
    serviceDefinitions?: Array<RegistrySvcDefinition>;
}

/**
 * Check if a given object implements the RegistrySvcListDefinitionsResponse interface.
 */
export function instanceOfRegistrySvcListDefinitionsResponse(value: object): value is RegistrySvcListDefinitionsResponse {
    return true;
}

export function RegistrySvcListDefinitionsResponseFromJSON(json: any): RegistrySvcListDefinitionsResponse {
    return RegistrySvcListDefinitionsResponseFromJSONTyped(json, false);
}

export function RegistrySvcListDefinitionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegistrySvcListDefinitionsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceDefinitions': json['serviceDefinitions'] == null ? undefined : ((json['serviceDefinitions'] as Array<any>).map(RegistrySvcDefinitionFromJSON)),
    };
}

export function RegistrySvcListDefinitionsResponseToJSON(value?: RegistrySvcListDefinitionsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'serviceDefinitions': value['serviceDefinitions'] == null ? undefined : ((value['serviceDefinitions'] as Array<any>).map(RegistrySvcDefinitionToJSON)),
    };
}

