/* tslint:disable */
/* eslint-disable */
/**
 * Superplatform
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RegistrySvcDefinition } from './RegistrySvcDefinition';
import {
    RegistrySvcDefinitionFromJSON,
    RegistrySvcDefinitionFromJSONTyped,
    RegistrySvcDefinitionToJSON,
} from './RegistrySvcDefinition';

/**
 * 
 * @export
 * @interface RegistrySvcSaveDefinitionRequest
 */
export interface RegistrySvcSaveDefinitionRequest {
    /**
     * 
     * @type {RegistrySvcDefinition}
     * @memberof RegistrySvcSaveDefinitionRequest
     */
    definition?: RegistrySvcDefinition;
}

/**
 * Check if a given object implements the RegistrySvcSaveDefinitionRequest interface.
 */
export function instanceOfRegistrySvcSaveDefinitionRequest(value: object): value is RegistrySvcSaveDefinitionRequest {
    return true;
}

export function RegistrySvcSaveDefinitionRequestFromJSON(json: any): RegistrySvcSaveDefinitionRequest {
    return RegistrySvcSaveDefinitionRequestFromJSONTyped(json, false);
}

export function RegistrySvcSaveDefinitionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegistrySvcSaveDefinitionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'definition': json['definition'] == null ? undefined : RegistrySvcDefinitionFromJSON(json['definition']),
    };
}

export function RegistrySvcSaveDefinitionRequestToJSON(value?: RegistrySvcSaveDefinitionRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'definition': RegistrySvcDefinitionToJSON(value['definition']),
    };
}

