/* tslint:disable */
/* eslint-disable */
/**
 * Singulatron
 * Run and develop self-hosted AI apps. Your programmable in-house GPT. The Firebase for the AI age.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UsertypesUser } from './UsertypesUser';
import {
    UsertypesUserFromJSON,
    UsertypesUserFromJSONTyped,
    UsertypesUserToJSON,
} from './UsertypesUser';

/**
 * 
 * @export
 * @interface UsertypesReadUserByTokenResponse
 */
export interface UsertypesReadUserByTokenResponse {
    /**
     * 
     * @type {UsertypesUser}
     * @memberof UsertypesReadUserByTokenResponse
     */
    user?: UsertypesUser;
}

/**
 * Check if a given object implements the UsertypesReadUserByTokenResponse interface.
 */
export function instanceOfUsertypesReadUserByTokenResponse(value: object): value is UsertypesReadUserByTokenResponse {
    return true;
}

export function UsertypesReadUserByTokenResponseFromJSON(json: any): UsertypesReadUserByTokenResponse {
    return UsertypesReadUserByTokenResponseFromJSONTyped(json, false);
}

export function UsertypesReadUserByTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsertypesReadUserByTokenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'user': json['user'] == null ? undefined : UsertypesUserFromJSON(json['user']),
    };
}

export function UsertypesReadUserByTokenResponseToJSON(value?: UsertypesReadUserByTokenResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'user': UsertypesUserToJSON(value['user']),
    };
}

