/* tslint:disable */
/* eslint-disable */
/**
 * Superplatform
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserSvcCreateRoleRequest
 */
export interface UserSvcCreateRoleRequest {
    /**
     * 
     * @type {string}
     * @memberof UserSvcCreateRoleRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UserSvcCreateRoleRequest
     */
    name?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserSvcCreateRoleRequest
     */
    permissionIds?: Array<string>;
}

/**
 * Check if a given object implements the UserSvcCreateRoleRequest interface.
 */
export function instanceOfUserSvcCreateRoleRequest(value: object): value is UserSvcCreateRoleRequest {
    return true;
}

export function UserSvcCreateRoleRequestFromJSON(json: any): UserSvcCreateRoleRequest {
    return UserSvcCreateRoleRequestFromJSONTyped(json, false);
}

export function UserSvcCreateRoleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSvcCreateRoleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'name': json['name'] == null ? undefined : json['name'],
        'permissionIds': json['permissionIds'] == null ? undefined : json['permissionIds'],
    };
}

export function UserSvcCreateRoleRequestToJSON(value?: UserSvcCreateRoleRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'description': value['description'],
        'name': value['name'],
        'permissionIds': value['permissionIds'],
    };
}

