/* tslint:disable */
/* eslint-disable */
/**
 * Singulatron
 * Run and develop self-hosted AI apps. Your programmable in-house GPT. The Firebase for the AI age.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsertypesChangePasswordAdminRequest
 */
export interface UsertypesChangePasswordAdminRequest {
    /**
     * 
     * @type {string}
     * @memberof UsertypesChangePasswordAdminRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UsertypesChangePasswordAdminRequest
     */
    newPassword?: string;
}

/**
 * Check if a given object implements the UsertypesChangePasswordAdminRequest interface.
 */
export function instanceOfUsertypesChangePasswordAdminRequest(value: object): value is UsertypesChangePasswordAdminRequest {
    return true;
}

export function UsertypesChangePasswordAdminRequestFromJSON(json: any): UsertypesChangePasswordAdminRequest {
    return UsertypesChangePasswordAdminRequestFromJSONTyped(json, false);
}

export function UsertypesChangePasswordAdminRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsertypesChangePasswordAdminRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'newPassword': json['newPassword'] == null ? undefined : json['newPassword'],
    };
}

export function UsertypesChangePasswordAdminRequestToJSON(value?: UsertypesChangePasswordAdminRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'newPassword': value['newPassword'],
    };
}

