/* tslint:disable */
/* eslint-disable */
/**
 * Superplatform
 * On-premise AI platform and microservices ecosystem.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserSvcPermission } from './UserSvcPermission';
import {
    UserSvcPermissionFromJSON,
    UserSvcPermissionFromJSONTyped,
    UserSvcPermissionToJSON,
} from './UserSvcPermission';

/**
 * 
 * @export
 * @interface UserSvcGetPermissionsResponse
 */
export interface UserSvcGetPermissionsResponse {
    /**
     * 
     * @type {Array<UserSvcPermission>}
     * @memberof UserSvcGetPermissionsResponse
     */
    permissions?: Array<UserSvcPermission>;
}

/**
 * Check if a given object implements the UserSvcGetPermissionsResponse interface.
 */
export function instanceOfUserSvcGetPermissionsResponse(value: object): value is UserSvcGetPermissionsResponse {
    return true;
}

export function UserSvcGetPermissionsResponseFromJSON(json: any): UserSvcGetPermissionsResponse {
    return UserSvcGetPermissionsResponseFromJSONTyped(json, false);
}

export function UserSvcGetPermissionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSvcGetPermissionsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'permissions': json['permissions'] == null ? undefined : ((json['permissions'] as Array<any>).map(UserSvcPermissionFromJSON)),
    };
}

export function UserSvcGetPermissionsResponseToJSON(value?: UserSvcGetPermissionsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'permissions': value['permissions'] == null ? undefined : ((value['permissions'] as Array<any>).map(UserSvcPermissionToJSON)),
    };
}

