/* tslint:disable */
/* eslint-disable */
/**
 * Singulatron
 * Run and develop self-hosted AI apps. Your programmable in-house GPT. The Firebase for the AI age.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserSvcSaveProfileRequest
 */
export interface UserSvcSaveProfileRequest {
    /**
     * 
     * @type {string}
     * @memberof UserSvcSaveProfileRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UserSvcSaveProfileRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the UserSvcSaveProfileRequest interface.
 */
export function instanceOfUserSvcSaveProfileRequest(value: object): value is UserSvcSaveProfileRequest {
    return true;
}

export function UserSvcSaveProfileRequestFromJSON(json: any): UserSvcSaveProfileRequest {
    return UserSvcSaveProfileRequestFromJSONTyped(json, false);
}

export function UserSvcSaveProfileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSvcSaveProfileRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function UserSvcSaveProfileRequestToJSON(value?: UserSvcSaveProfileRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'name': value['name'],
    };
}

