/* tslint:disable */
/* eslint-disable */
/**
 * Singulatron
 * Run and develop self-hosted AI apps. Your programmable in-house GPT. The Firebase for the AI age.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsertypesReadUserByTokenRequest
 */
export interface UsertypesReadUserByTokenRequest {
    /**
     * 
     * @type {string}
     * @memberof UsertypesReadUserByTokenRequest
     */
    token?: string;
}

/**
 * Check if a given object implements the UsertypesReadUserByTokenRequest interface.
 */
export function instanceOfUsertypesReadUserByTokenRequest(value: object): value is UsertypesReadUserByTokenRequest {
    return true;
}

export function UsertypesReadUserByTokenRequestFromJSON(json: any): UsertypesReadUserByTokenRequest {
    return UsertypesReadUserByTokenRequestFromJSONTyped(json, false);
}

export function UsertypesReadUserByTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsertypesReadUserByTokenRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'] == null ? undefined : json['token'],
    };
}

export function UsertypesReadUserByTokenRequestToJSON(value?: UsertypesReadUserByTokenRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'token': value['token'],
    };
}

