/* tslint:disable */
/* eslint-disable */
/**
 * Singulatron
 * Run and develop self-hosted AI apps. Your programmable in-house GPT. The Firebase for the AI age.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserSvcRegisterRequest
 */
export interface UserSvcRegisterRequest {
    /**
     * 
     * @type {string}
     * @memberof UserSvcRegisterRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UserSvcRegisterRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UserSvcRegisterRequest
     */
    password?: string;
}

/**
 * Check if a given object implements the UserSvcRegisterRequest interface.
 */
export function instanceOfUserSvcRegisterRequest(value: object): value is UserSvcRegisterRequest {
    return true;
}

export function UserSvcRegisterRequestFromJSON(json: any): UserSvcRegisterRequest {
    return UserSvcRegisterRequestFromJSONTyped(json, false);
}

export function UserSvcRegisterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSvcRegisterRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'name': json['name'] == null ? undefined : json['name'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function UserSvcRegisterRequestToJSON(value?: UserSvcRegisterRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'name': value['name'],
        'password': value['password'],
    };
}

