/* tslint:disable */
/* eslint-disable */
/**
 * Singulatron
 * Run and develop self-hosted AI apps. Your programmable in-house GPT. The Firebase for the AI age.
 *
 * The version of the OpenAPI document: 0.2
 * Contact: sales@singulatron.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsertypesRole
 */
export interface UsertypesRole {
    /**
     * 
     * @type {string}
     * @memberof UsertypesRole
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof UsertypesRole
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UsertypesRole
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UsertypesRole
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UsertypesRole
     */
    ownerId?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UsertypesRole
     */
    permissionIds?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof UsertypesRole
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the UsertypesRole interface.
 */
export function instanceOfUsertypesRole(value: object): value is UsertypesRole {
    return true;
}

export function UsertypesRoleFromJSON(json: any): UsertypesRole {
    return UsertypesRoleFromJSONTyped(json, false);
}

export function UsertypesRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsertypesRole {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'ownerId': json['ownerId'] == null ? undefined : json['ownerId'],
        'permissionIds': json['permissionIds'] == null ? undefined : json['permissionIds'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
    };
}

export function UsertypesRoleToJSON(value?: UsertypesRole | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'createdAt': value['createdAt'],
        'description': value['description'],
        'id': value['id'],
        'name': value['name'],
        'ownerId': value['ownerId'],
        'permissionIds': value['permissionIds'],
        'updatedAt': value['updatedAt'],
    };
}

